services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

    oauth:
    build: ./oauth-server
    ports:
      - "9000:9000"
    env_file:
      - ./oauth-server/.env

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      API_BASE_URL: http://backend:8000
      PUBLIC_API_BASE_URL: http://localhost:8000
      PUBLIC_OAUTH_BASE_URL: http://localhost:9000
      PUBLIC_OAUTH_CLIENT_ID: cybercart
      PUBLIC_OAUTH_ATTACKER_REDIRECT_URI: https://layer8-attacker.up.railway.app/oauth/callback
    depends_on:
      - backend
      - oauth

  attacker-site:
    build: ./attacker-site
    ports:
      - "7001:7001"
